[package]
name = "mktape"
version = "2.0.0"
edition = "2021"

[dev-dependencies]
openssl = "0.10.63"

[dependencies]
cargo = "0.76.0"
clap = { version = "4", features = ["derive"] }
features = "0.10.0"
regex = "1.10.3"
