# Run acceptance-cycle on develop commits.
#
# Acceptance cycle comprises:
# - run tests on develop
# - release into main with bumped versions
#
name: Acceptance Cycle

on:
  push:
    branches:
      - develop

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Prep
        run: |
          sudo apt update
          sudo apt install curl

      - name: Checkout
        uses: actions/checkout@v3

      # - name: License Header Check
      #   run: sbt headerCheck

      - name: Test
        run: |
          cd data
          curl -LO https://www.tuhs.org/Archive/Distributions/Research/Keith_Bostic_v7/f0.gz
          curl -LO https://www.tuhs.org/Archive/Distributions/Research/Keith_Bostic_v7/f1.gz
          curl -LO https://www.tuhs.org/Archive/Distributions/Research/Keith_Bostic_v7/f2.gz
          curl -LO https://www.tuhs.org/Archive/Distributions/Research/Keith_Bostic_v7/f3.gz
          curl -LO https://www.tuhs.org/Archive/Distributions/Research/Keith_Bostic_v7/f4.gz
          curl -LO https://www.tuhs.org/Archive/Distributions/Research/Keith_Bostic_v7/f5.gz
          curl -LO https://www.tuhs.org/Archive/Distributions/Research/Keith_Bostic_v7/f6.gz
          gunzip f*.gz
          cargo install cargo-tarpaulin
          cargo tarpaulin --out xml

      - name: Publish to Codecov
        uses: codecov/codecov-action@v3

      - name: Documentation
        run: cargo doc

  release:
    needs: acceptance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run: |
          git config --global user.email "nigeleke@users.noreply.github.com"
          git config --global user.name "Nigel Eke"
          git checkout main
          git merge develop
          cargo install cargo-workspaces
          cargo workspaces -v version --allow-branch main --yes patch
